spring:
  application:
    name: 用户管理中心
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/PersonalBlog
    username: root
    password: 749813
server:
  port: 8080
  servlet:
    context-path: /api/
mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: is_dalete # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)